apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: consistency-report
provisioner: cephfs.csi.ceph.com
parameters:
  monitors: 128.142.39.77:6790,128.142.39.144:6790,188.184.86.25:6790,188.184.94.56:6790,188.185.66.208:6790
  provisionVolume: "false"

  # Required if provisionVolume is set to false
  rootPath: /volumes/_nogroup/pvc-58965267-ada4-432b-b900-b5b095757d5c

  # The secret has to contain user and/or admin credentials.
  csiProvisionerSecretName: csi-cephfs-secret
  csiProvisionerSecretNamespace: default
  csiNodeStageSecretName: csi-cephfs-secret
  csiNodeStageSecretNamespace: default

reclaimPolicy: Retain
