
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc
spec:
  accessModes:
  - ReadOnly
  storageClassName: csi-cephfs

---

kind: Service
apiVersion: v1
metadata:
  name: cmscon-monitor
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 8080 
    protocol: TCP
    name: http
  selector:
    app: cmscon-monitor
  
---
    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: cmscon-monitor
  name: cmscon-monitor
  namespace: http
spec:
  selector:
    matchLabels:
      app: cmscon-monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: cmscon-monitor
    spec:
      containers:
      - image: ivmfnal/cmscon-monitor #imagetag
        name: cmscon-monitor
        livenessProbe:
          httpGet:
            path: /probe
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8080
        
        
---
apiVersion: v1
kind: Pod
metadata:
  name: cmscon-monitor
spec:
  containers:
   - name: cmscon-monitor
     image: ivmfnal/cmscon-monitor
     volumeMounts:
       - mountPath: /samples
         name: mypvc
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: csi-cephfs-pvc
       readOnly: true