kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consistency-report-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1G
  storageClassName: consistency-report
