
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: consistency-report-pvc
spec:
  accessModes:
    - ReadOnly
  resources:
    requests:
      storage: 1GB
  storageClassName: meyrin-cephfs
---

kind: Service
apiVersion: v1
metadata:
  name: rucio_consistency_monitor
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 8080 
    protocol: TCP
    name: http
  selector:
    app: rucio_consistency_monitor
  
---
    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: rucio_consistency_monitor
  name: rucio_consistency_monitor
  namespace: http
spec:
  selector:
    matchLabels:
      app: rucio_consistency_monitor
  replicas: 1
  template:
    metadata:
      labels:
        app: rucio_consistency_monitor
    spec:
      containers:
      - image: ivmfnal/rucio_consistency_monitor
        name: rucio_consistency_monitor
        livenessProbe:
          httpGet:
            path: /probe
            port: 8400
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8400
        volumeMounts:
            - mountPath: /samples
              name: consistency-report-pvc
