kind: Service
apiVersion: v1
metadata:
  name: rucio-consistency-monitor
  namespace: http
spec:
  type: ClusterIP
  ports:
  - port: 8400
    protocol: TCP
    name: http
  selector:
    app: rucio_consistency_monitor
  
